version: '2'

name: pt-magento2

services:

  magento:
    image: docker.io/bitnami/magento:2
    container_name: pt-magento2-site
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - MAGENTO_HOST=localhost
      - MAGENTO_DATABASE_HOST=mariadb
      - MAGENTO_DATABASE_PORT_NUMBER=3306
      - MAGENTO_DATABASE_USER=bn_magento
      - MAGENTO_DATABASE_NAME=bitnami_magento
      # - MAGENTO_EXTERNAL_HTTP_PORT_NUMBER=780
      # - MAGENTO_EXTERNAL_HTTPS_PORT_NUMBER=7443
      - MAGENTO_USERNAME=admin
      - MAGENTO_PASSWORD=Pass@123
      - MAGENTO_ENABLE_HTTPS=yes
      # - MAGENTO_EXTRA_INSTALL_ARGS="--currency=AED"
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT_NUMBER=9200
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - site:/bitnami/magento
      - ../paytabs-magento2.x:/bitnami/magento/app/code/PayTabs/PayPage:rw
    depends_on:
      mariadb:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    container_name: pt-magento2-db
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_magento
      - MARIADB_DATABASE=bitnami_magento
    volumes:
      - db:/bitnami/mariadb
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent" ]
      interval: 5s
      timeout: 60s
      retries: 5
      start_period: 30s

  elasticsearch:
    image: docker.io/bitnami/elasticsearch:7
    container_name: pt-magento2-elasticsearch
    volumes:
      - elasticsearch:/bitnami/elasticsearch/data
    healthcheck:
      test: curl -s http://elasticsearch:9200 >/dev/null || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  db:
    driver: local
  site:
    driver: local
  elasticsearch:
    driver: local
